server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    log-startup-info: false
    banner-mode: off
  cloud:
    gateway:
      discovery.locator.enabled: true # использование Discovery Service
      routes:
        - id: shopping_cart_service_route # название маршрута
          uri: lb://shopping-cart # перенаправлять в shopping-cart через load balancer
          predicates:
            - Path=/shopping-cart/** # запросы которые начинаются с /shopping-cart/
          filters:
            - PrefixPath=/api/v1 # к запросу добавить префикс /api/v1

#        - id: shopping_cart_circuitbreaker_route
#          uri: lb://shopping-cart
#          predicates:
#            - Path=/shopping-cart/**
#          filters:
#            - CircuitBreaker=myCircuitBreaker

        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3 # количество повторных попыток
                exceptions: util.exception.ProductNotFoundException # попытки только для этого исключения + по умолчанию для IOException, TimeoutException, RetryException
                methods: GET, POST, PUT # только для этих методов
                backoff:
                  firstBackoff: 250ms # задержка перед первой повторной попыткой
                  maxBackoff: 500ms # максимальная задержка между попытками
                  factor: 2 # множитель для экспоненциального роста задержки
                  basedOnPreviousValue: false # каждая задержка рассчитывается на основе предыдущей задержки

        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1

        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1

        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1

        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, gateway
  endpoint:
    gateway:
      enabled: true # для просмотра gateway/routes

logging:
  level:
    root: INFO