server:
  port: 8761

spring:
  main:
    log-startup-info: false
    banner-mode: off

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # не регистрируемся в eureka
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/