spring:
  application:
    name: collector
  config:
    import: "configserver:" # external configuration with eureka
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true # падаем если config-server недоступен
      retry:
        use-random-policy: true # между попытками «случайная экспоненциальная выдержка»
        max-interval: 2000 # max интервал между попытками
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    instance: # описание экземпляров текущего сервиса
      prefer-ip-address: true # регистрировать этот сервис по IP-адресу
      hostname: localhost
      instance-id: "${spring.application.name}:${random.value}" # уникальный ID конкретного экземпляра сервиса
      lease-renewal-interval-in-seconds: 10 # interval health checkов в eureka