server:
  port: 9093

grpc:
  server:
    port: 59091

spring:
  application:
    name: collector
  main:
    log-startup-info: false
    banner-mode: off
  kafka:
    properties:
      bootstrap.servers: "localhost:9092"
      key.serializer: "org.apache.kafka.common.serialization.VoidSerializer"
      producer:
        linger-ms: 5

kafka:
  topics:
    sensor-events: "telemetry.sensors.v1"
    hub-events: "telemetry.hubs.v1"
    events-snapshots: "telemetry.snapshots.v1"
  groups:
    aggregator: "aggregator-group"

logging:
  level:
    org.springframework.context: ERROR
    org.apache.kafka: ERROR