spring:
  application:
    name: aggregator
  config:
    import: configserver:http://localhost:8888 # external configuration
  cloud:
    config:
      fail-fast: true # падаем если config-server недоступен
      retry:
        use-random-policy: true # между попытками «случайная экспоненциальная выдержка»
        max-interval: 2000 # max интервал между попытками