spring:
  application:
    name: shopping-store
  config:
    import: "configserver:" # external configuration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true # падаем если config-server недоступен
      retry:
        use-random-policy: true # между попытками «случайная экспоненциальная выдержка»
        max-interval: 2000 # max интервал между попытками
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/